### ISSUE TITLE
How to use it in LineageOS 17.1 source tree?

### ISSUE THREAD

**Issue by andersling** [hkoosha/lineage_device_arpi_rpi4#1]
Thanks for you great work!!!
I try to git clone it int the [device/endorphin/erpi4] dir ,choose erpi4_userdebug and build it ,and after that i callthe mkimg.sh in  that folder,and i get [endorphin--lineage--20200816--rpi4.img] image, and then ,i write it to  sd  card and insert it into the rpi4b ,but i can't boot it. i event can't see the rainbow screen but the error screen with a  raspberry logo!

 And by the way , is that i need to sync other Repositories such as android_hardware_rpi4 ?

thanks !
waiting for you reply! my email is :andersling@qq.com.
best regards!

**Comment by hkoosha** [comment]
Hi
You should closely follow the instructions from https://github.com/android-rpi/device_arpi_rpi4, get the localmanifest from there.
Then as a final step, just replace the device with erpi. so yes you need other repos synced too.

However, if you look in the issues there at android-rpi/device_arpi_rpi4, someone has posted a more updated, and more stable! version of lineage for rpi. I suggest you build from that device.

**Comment by andersling** [comment]
Thank you very much,sir! And by the way, had  you ever successfully compiled  lineage_rpi ? I have downloadthe lineaos source code and the lineage_rpi ( https://github.com/lineage-rpi ) ,but i can't build it successfully for RPI4B . and ,as for Kongka's image (https://konstakang.com/devices/rpi4/LineageOS17.1/) I can't boot it up,it keep booting again and again when the lineage animation finished!
  thanks!

**Comment by hkoosha** [comment]
No I had never any luck with that repo from Konsta, but his images usually work pretty good and are quite stable. Are you sure there's nothing wrong with the RPi itself?
Maybe try a raspian image see if it boots and device is working correctly?
I also suggest building the original repo from peter yoon (https://github.com/android-rpi/device_arpi_rpi4) and only if you got that one working, moving onto lineage afterwards.

**Comment by andersling** [comment]
> No I had never any luck with that repo from Konsta, but his images usually work pretty good and are quite stable. Are you sure there's nothing wrong with the RPi itself?
> Maybe try a raspian image see if it boots and device is working correctly?
> I also suggest building the original repo from peter yoon (https://github.com/android-rpi/device_arpi_rpi4) and only if you got that one working, moving onto lineage afterwards.

Thanks for your kindly tips!!~ 
I have try Konsta's Room in rpi3b, rpi4b 2G/4G/8G ,it's the same result----when  booting animation finished,it reboot again and again.
and by the way, How  can I  see the debug message (I am new to kernel debuging,sorry!)? would you do me a fover to give me some instructions? Thanks,sir!

**Comment by hkoosha** [comment]
Well for that you will need a usb to serial cable. Do you have one?
And please please please, be very careful not to connect the red wire to your RPi and use a resistor on the tx line. 
You can search on google for raspberry usb to serial.

**Comment by andersling** [comment]
> I also suggest building the original repo from peter yoon (https://github.com/android-rpi/device_arpi_rpi4) and only if you got that one working, moving onto lineage afterwards.

and I have build peter yoon''s original room,and it's OK boot into the UI, but it has a big issue: NO WIFI,and the ethernet shows "not connected" but actrual it has connected to my route already. The big problem is when I try to enabled WIFI in the setting UI,It reboots, maybe it's the wlan0 driver's problem!
Thanks!

**Comment by hkoosha** [comment]
For wifi it's the best to see the logs, you definitely need the USB2Serial cable.

**Comment by andersling** [comment]
> Well for that you will need a usb to serial cable. Do you have one?
> And please please please, be very careful not to connect the red wire to your RPi and use a resistor on the tx line.
> You can search on google for raspberry usb to serial.

Big thanks! I try to buy one and try it, you are so kind! Thanks.........
